#!/bin/bash
# Configure step-ca's ACME provisioner to issue 7-day (168h) leaf certs
# instead of the smallstep default 24h. Without this, every Traefik in
# the homelab gets 24h certs and one missed renewal cycle (e.g., a brief
# pki.lan outage while traefik is doing its hourly ACME check) cascades
# into all-services-down within the day. 7d gives ~6 cycles of headroom.
#
# Idempotent: silent no-op when claims are already set.
#
# RUN THIS:
#   - Once after first bootstrap of cn-pki (smallstep's DOCKER_STEPCA_INIT_*
#     env vars generate a default ca.json that does NOT include claims).
#   - After any reset/recreate of the step_ca_data volume.
#   - After any other tooling that rewrites /home/step/config/ca.json.
#
# Why a script vs. baking it into docker-compose: ca.json is generated by
# smallstep/step-ca's init logic at first boot inside the step_ca_data
# volume, and contains per-instance secrets (JWK provisioner encrypted
# key). It can't be a bind-mount from git. The runtime patch is the
# durable mechanism.

set -euo pipefail

CONTAINER="${STEPCA_CONTAINER:-cn-pki-step-ca-1}"

if ! docker inspect "$CONTAINER" >/dev/null 2>&1; then
  echo "ERROR: container $CONTAINER not found. Is cn-pki running on this host?" >&2
  exit 1
fi

CURRENT=$(docker exec "$CONTAINER" cat /home/step/config/ca.json)
NEW=$(echo "$CURRENT" | python3 -c '
import json, sys
c = json.load(sys.stdin)
for p in c["authority"]["provisioners"]:
    if p.get("type","").lower() == "acme":
        p["claims"] = {
            "defaultTLSCertDuration": "168h",
            "maxTLSCertDuration":     "168h",
            "minTLSCertDuration":     "5m",
        }
sys.stdout.write(json.dumps(c, indent="\t"))
')

if [[ "$CURRENT" == "$NEW" ]]; then
  echo "step-ca ACME claims already configured for 168h leaves — no change."
  exit 0
fi

echo "Patching step-ca ACME provisioner: 168h leaves..."
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
printf '%s' "$NEW" > "$TMP"
docker cp "$TMP" "$CONTAINER":/home/step/config/ca.json

echo "Restarting step-ca..."
docker restart "$CONTAINER" >/dev/null

# step-ca takes ~3-5s to come back; poll until healthy.
for _ in 1 2 3 4 5 6 7 8 9 10; do
  if curl -sk -o /dev/null -w '%{http_code}' --max-time 2 https://pki.lan:9000/health 2>/dev/null | grep -q '^200$'; then
    echo "step-ca healthy. 7-day leaves are now the default for ACME orders."
    exit 0
  fi
  sleep 1
done

echo "WARN: step-ca did not return 200 on /health within 10s. Check 'docker logs $CONTAINER'." >&2
exit 2
